// Teste do endpoint dos usuarios

@baseURL = http://localhost:4000/api/usuarios

###
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "José Lima Alves",
    "email": "josealves@uol.com.br",
    "senha": "123Mudar"
}